### ISSUE TITLE
Error importing module: No module named 'matplotlib._docstring'

### ISSUE THREAD

**Issue by ferokko** [PMEAL/porespy#902]
Hi all, 

I am using the porespy library on a databricks environment, python Python 3.10.12. I have been using it for 2 years now, but in the last 6 months I didn't use it anymore.

I need to use it again now and I needed to create a new compute instance on databricks. I installed the library in the compute cluster like any other library, version 2.3.0. The installation is via pip.

In the notebook code, during the import phase I get this error

`import porespy as ps`
`ModuleNotFoundError: No module named 'matplotlib._docstring'`

Any idea why? 

Thanks!

**Comment by jgostick** [comment]
The problem is coming from openpnm, which porespy installs.  The "root" problem is that your databricks instance seems to be using an old matplotlib version.  We fixed this in openpnm, but our fix was not general enough to handle new and old versions of openpnm.  I have patched this on the dev branch of openpnm but had not merged it into a release yet.  I will do today. 

https://github.com/PMEAL/OpenPNM/pull/2857

**Comment by ferokko** [comment]
Hi @jgostick , thanks a lot! Indeed I saw on openpnm GH that there was the try/catch in the _doctxt function but the version I am using on the cluster still shows the older version. Will this be integrated into the porespy version 2.3.0 on the pypi ?

**Comment by jgostick** [comment]
I was going to do it today but the windows builds are all failing for unknown reasons. I was hoping this problem would fix itself (i.e. a github problem), but I'm still waiting.  I will merge asap.
