### ISSUE TITLE
Throat diameter is larger than the diameter of one connection pore body.

### ISSUE THREAD

**Issue by hefnymah** [PMEAL/porespy#97]
the extracted pore-network from CT images using porespy has some throat which its diameter is larger than the diameter of one of the pore body connected to it ( some time is 123 % larger). in case of the small pore is flat. However, in the pore-network modeling and percolation theory, it assumes that the throat should be smaller than the pore-body. Any suggestion to overcome this issue,
thank you very much for your help in advance,
Hefny

**Comment by TomTranter** [comment]
Addressed by #98

**Comment by TomTranter** [comment]
Woops, closed wrong issue

**Comment by jgostick** [comment]
This is partially fixed.  It was caused by a changed I'd introduced that moved the pore centers away from where the distance transform said they should be.  We've reversed this now...however, there is still no guarantee that this won't happen and we don't currently check for it.  It would be wise to improve the ``regions_to_network`` function to include such a check.

**Comment by jgostick** [comment]
The latest version is 1.1.2 I think.  We recently gave it the 1.0 mark, and published a paper in Journal of Open Source Software

**Comment by raincoder87** [comment]
Hey, I am kindly wondering for more detail how you partially fixed it. I'm still facing the same problem described above.
where in the code that can eliminate that effect?
thanks for help in advance,

**Comment by jgostick** [comment]
This could happen if the pores have an aspect ratio > 1.  If the pore is like a pancake, then you can only draw a small sphere inside it, but the throats could still be quite large.  We are currently thinking of ways to extract the geometrical information more robustly, but as of now the implementation in porespy does not check for things like this.  It is not hard to fix after the fact though once you have it in openpnm and you notice the problem....just over write the pore and/or throat diameter.  Sorry I don't have a better answer for you.  

I will move this higher in priority, so we can get better geometrical info during the extraction phase.

**Comment by jgostick** [comment]
Having given this some thought, here is my view.  Although large throats break the pnm paradigm (sort of), they are not necessarily unphysical.  There are for sure cases where the pore flattened so it's diameter is small, the throat can be wide.  Setting this situation as 'invalid' is not fair.  Luckily, openpnm now has a new set of conductance models that can deal with this.

There are a few cases, given Pore A and B, and throat C:

1. If C is larger than either A or B (but not both), then the geometry is well approximated by a cone.  
2. If C is larger than BOTH A and B, then things are problematic.  We need to add a new model to openpnm that deals with 'diverging cones'.  

I am going to close this, on the basis that such throats are physical, and I'm going to open an issue on openpnm about adding a diverging cones model.
